# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\MUHAMMET MUSTAFA\Desktop\Software\Python Projeler\pyqt5\hesap_makinesi(-)\hes_mak.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(240, 361)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 239, 71))
        self.label.setStyleSheet("QLabel{\n"
"color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 75 20pt \"MS Shell Dlg 2\";\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.pushButton_C = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_C.setGeometry(QtCore.QRect(0, 64, 61, 61))
        self.pushButton_C.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(172, 172, 172);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(172, 172, 172);\n"
"}")
        self.pushButton_C.setObjectName("pushButton_C")
        self.pushButton_degis = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_degis.setGeometry(QtCore.QRect(60, 64, 61, 61))
        self.pushButton_degis.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(172, 172, 172);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(172, 172, 172);\n"
"}")
        self.pushButton_degis.setObjectName("pushButton_degis")
        self.pushButton_yuzde = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_yuzde.setGeometry(QtCore.QRect(120, 64, 61, 61))
        self.pushButton_yuzde.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(172, 172, 172);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(172, 172, 172);\n"
"}")
        self.pushButton_yuzde.setObjectName("pushButton_yuzde")
        self.pushButton_bolme = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_bolme.setGeometry(QtCore.QRect(180, 64, 61, 61))
        self.pushButton_bolme.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(122, 122, 122);\n"
"}")
        self.pushButton_bolme.setObjectName("pushButton_bolme")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(120, 123, 61, 61))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 123, 61, 61))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(60, 123, 61, 61))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_carp = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_carp.setGeometry(QtCore.QRect(180, 123, 61, 61))
        self.pushButton_carp.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(122, 122, 122);\n"
"}")
        self.pushButton_carp.setObjectName("pushButton_carp")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(120, 182, 61, 61))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 182, 61, 61))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_art = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_art.setGeometry(QtCore.QRect(180, 241, 61, 61))
        self.pushButton_art.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(122, 122, 122);\n"
"}")
        self.pushButton_art.setObjectName("pushButton_art")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(60, 182, 61, 61))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(0, 241, 61, 61))
        self.pushButton_1.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 241, 61, 61))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(119, 241, 61, 61))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_eksi = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_eksi.setGeometry(QtCore.QRect(180, 182, 61, 61))
        self.pushButton_eksi.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(122, 122, 122);\n"
"}")
        self.pushButton_eksi.setObjectName("pushButton_eksi")
        self.pushButton_nokta = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_nokta.setGeometry(QtCore.QRect(120, 300, 61, 61))
        self.pushButton_nokta.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(76, 76,76);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(76,76,76);\n"
"}")
        self.pushButton_nokta.setObjectName("pushButton_nokta")
        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_0.setGeometry(QtCore.QRect(0, 300, 121, 61))
        self.pushButton_0.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}")
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_esittir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_esittir.setGeometry(QtCore.QRect(180, 300, 61, 61))
        self.pushButton_esittir.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(122, 122, 122);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 75 18pt \"MS Shell Dlg 2\";\n"
"    color: rgb(122, 122, 122);\n"
"}")
        self.pushButton_esittir.setObjectName("pushButton_esittir")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        MainWindow.setWindowIcon(QIcon('calculator.png'))
        self.label.setText(_translate("MainWindow", "0"))
        self.pushButton_C.setText(_translate("MainWindow", "C"))
        self.pushButton_degis.setText(_translate("MainWindow", "+/-"))
        self.pushButton_yuzde.setText(_translate("MainWindow", "%"))
        self.pushButton_bolme.setText(_translate("MainWindow", "/"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_carp.setText(_translate("MainWindow", "X"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_art.setText(_translate("MainWindow", "+"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_eksi.setText(_translate("MainWindow", "-"))
        self.pushButton_nokta.setText(_translate("MainWindow", "."))
        self.pushButton_0.setText(_translate("MainWindow", "0"))
        self.pushButton_esittir.setText(_translate("MainWindow", "="))
